version: '3.9'
services:

### POSTGRES DATABASE  ###
    postgres:
        image: postgres:14-alpine
        restart: always
        ports: 
          - "5432:5432"
        environment:
              POSTGRES_DB: Costs
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: 15963480
        networks:
          - postgres
        volumes:
          - pgdata:/var/lib/postgresql/data

    
### API Spring Boot ###
    api:
      build:
        dockerfile: Dockerfile 
        context: ./cost-server
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgresql://postgres:5432/Costs
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: 15963480
      ports:
        - "8080:8080"
      networks:
        - postgres

    interface:
      build:
        dockerfile: Dockerfile
        context: ./cost-interface
      ports:
       - "3000:80"
volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
    ipam:
      driver: default
